# Generated by Django 4.2 on 2023-04-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='woman',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
